import { palette } from '@/src/ui/palette';

export const markdownStyleSource = {
  body: {
    color: palette.text,
    fontSize: 14,
    lineHeight: 20,
  },
  heading1: { color: palette.text, fontSize: 20, lineHeight: 25, fontWeight: '700' as const, marginTop: 10, marginBottom: 5 },
  heading2: { color: palette.text, fontSize: 18, lineHeight: 23, fontWeight: '700' as const, marginTop: 8, marginBottom: 4 },
  heading3: { color: palette.text, fontSize: 16, lineHeight: 21, fontWeight: '700' as const, marginTop: 7, marginBottom: 3 },
  paragraph: { marginTop: 0, marginBottom: 6 },
  strong: { color: palette.text, fontWeight: '700' as const },
  em: { color: palette.text },
  s: { color: palette.textMuted },
  link: { color: palette.primary, textDecorationLine: 'underline' as const },
  blockquote: {
    borderLeftWidth: 2,
    borderLeftColor: palette.borderActive,
    paddingLeft: 10,
    backgroundColor: palette.backgroundElement,
  },
  code_inline: {
    color: palette.warning,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: 0,
    padding: 0,
    fontFamily: 'SpaceMono',
    fontSize: 13,
    lineHeight: 20,
  },
  fence: {
    color: palette.text,
    backgroundColor: palette.backgroundElement,
    borderColor: palette.borderSubtle,
    borderWidth: 1,
    padding: 10,
    fontFamily: 'SpaceMono',
    fontSize: 12,
    lineHeight: 18,
  },
  code_block: {
    color: palette.text,
    backgroundColor: palette.backgroundElement,
    borderColor: palette.borderSubtle,
    borderWidth: 1,
    padding: 10,
    fontFamily: 'SpaceMono',
    fontSize: 12,
    lineHeight: 18,
  },
  bullet_list: { marginBottom: 8 },
  ordered_list: { marginBottom: 8 },
  table: { borderWidth: 1, borderColor: palette.borderSubtle },
  tr: { borderBottomWidth: 1, borderColor: palette.borderSubtle },
  th: { padding: 6, backgroundColor: palette.backgroundElement, color: palette.text, fontWeight: '700' as const },
  td: { padding: 6, color: palette.text },
  hr: { backgroundColor: palette.borderSubtle, height: 1 },
};
