import type { OfficialOpenCodeThemeName } from './opencode-theme';

export const officialOpenCodeThemeAssetPaths: Record<OfficialOpenCodeThemeName, string> = {
  aura: 'assets/opencode-themes/aura.json',
  ayu: 'assets/opencode-themes/ayu.json',
  catppuccin: 'assets/opencode-themes/catppuccin.json',
  'catppuccin-frappe': 'assets/opencode-themes/catppuccin-frappe.json',
  'catppuccin-macchiato': 'assets/opencode-themes/catppuccin-macchiato.json',
  cobalt2: 'assets/opencode-themes/cobalt2.json',
  cursor: 'assets/opencode-themes/cursor.json',
  dracula: 'assets/opencode-themes/dracula.json',
  everforest: 'assets/opencode-themes/everforest.json',
  flexoki: 'assets/opencode-themes/flexoki.json',
  github: 'assets/opencode-themes/github.json',
  gruvbox: 'assets/opencode-themes/gruvbox.json',
  kanagawa: 'assets/opencode-themes/kanagawa.json',
  material: 'assets/opencode-themes/material.json',
  matrix: 'assets/opencode-themes/matrix.json',
  mercury: 'assets/opencode-themes/mercury.json',
  monokai: 'assets/opencode-themes/monokai.json',
  nightowl: 'assets/opencode-themes/nightowl.json',
  nord: 'assets/opencode-themes/nord.json',
  'one-dark': 'assets/opencode-themes/one-dark.json',
  'osaka-jade': 'assets/opencode-themes/osaka-jade.json',
  opencode: 'assets/opencode-themes/opencode.json',
  orng: 'assets/opencode-themes/orng.json',
  'lucent-orng': 'assets/opencode-themes/lucent-orng.json',
  palenight: 'assets/opencode-themes/palenight.json',
  rosepine: 'assets/opencode-themes/rosepine.json',
  solarized: 'assets/opencode-themes/solarized.json',
  synthwave84: 'assets/opencode-themes/synthwave84.json',
  tokyonight: 'assets/opencode-themes/tokyonight.json',
  vesper: 'assets/opencode-themes/vesper.json',
  vercel: 'assets/opencode-themes/vercel.json',
  zenburn: 'assets/opencode-themes/zenburn.json',
  carbonfox: 'assets/opencode-themes/carbonfox.json',
};
